### ISSUE TITLE
Add CBOR encapsulation support

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch-sql-odbc#152]
The current encapsulation possible is only JSON. For alignment to JDBC and some reduction of payload sizes, the binary CBOR format should be added.
A connection string option can then decide which format to choose at a connection level.

* [x] add in a CBOR library: #169 
* [x] add in decapsulation support of results: #172 
* [x] add in encapsulation support for parameters: #175 
* [x] extend testing: #177 
* [x] DSN editor configurable: #180

**Comment by bpintea** [comment]
Feature implemented.
