### ISSUE TITLE
BETA Todos

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-sql-odbc#51]
Branch from `master`, backport changes to `6.x`

- [x] Merge build processes for driver and MSI into a single build command. This is to simplify the build script process and remove the need to perform `cd <dir>` commands in the release manager. - @codebrain / @bpintea - #69 
- [ ] Unit / integration tests for editor dialog after moving to an MVVM or MVC architecture.- @codebrain 
- [x] Review `AssemblyInfo` version patching and ensure consistency across all .NET projects. - @codebrain - https://github.com/bpintea/elasticsearch-sql-odbc/tree/feature/integrate_installer_build
- [x] Consolidate `.gitignore` files across the repo. - @codebrain  - https://github.com/elastic/elasticsearch-sql-odbc/pull/71
- [x] Ensure copyright year is present in `AssemblyInfo` files. - @codebrain to find out if needed (none of the other DLLs use year). - https://github.com/bpintea/elasticsearch-sql-odbc/tree/feature/integrate_installer_build
- [x] Align the editor to either all tabs or all space. (The driver uses tabs, but we can delineate between the two). @codebrain to implement editor rules as defined by Microsoft team. - https://github.com/elastic/elasticsearch-sql-odbc/pull/67
- [x] Chain (tick-box-dependent) the _ODBC Data Source Administrator_ app to the installer - include getting started screen (as per Elasticsearch MSI) @codebrain - https://github.com/elastic/elasticsearch-sql-odbc/pull/65
- [ ] Considerations the VS redistributable @codebrain / @bpintea 
- [x] Documentation: installer @codebrain; editor @bpintea 
- [ ] Blog post prep @bpintea 
- [x] DSN editor tooltips? (optional) - https://github.com/elastic/elasticsearch-sql-odbc/pull/67
- 32-bit build (optional):
- [x] for the driver @bpintea - #76
- [x] for the installer @codebrain - #70, #74, #79
- [x] rename DSN binding DLL to include `32` for 32-bit builds; @bpintea - #63 
- [x] integrate x86 build into RM: https://github.com/elastic/release-manager/pull/506
- Validations on DSN editor for:
- [x] Name field - limit to registry key characters - https://github.com/elastic/elasticsearch-sql-odbc/pull/59
- [x] Ensure all field entries are no longer than 512 characters - https://github.com/elastic/elasticsearch-sql-odbc/pull/59
- [x] Launch ODBC editor on close (with checkbox) https://github.com/elastic/elasticsearch-sql-odbc/pull/79

**Comment by bpintea** [comment]
Repo is now public.

**Comment by codebrain** [comment]
@bpintea - Is it worth closing this ticket down and breaking out the remaining TODOS into their own tickets?

**Comment by bpintea** [comment]
Yes, makes sense.
I'll leave to you "Unit / integration tests for editor dialog after moving to an MVVM or MVC architecture".
Let's re-sync on "Considerations the VS redistributable".
I've started chatting to Shane on the blog post and will follow up.
